# Data Cleaning

In [41]:
#import packages
import numpy as np #for array and matrices
import pandas as pd #for data manipulation and analysis
from sklearn.model_selection  import train_test_split #for split the data into train and test
from sklearn import preprocessing # for preprocessing of data

In [42]:
#load the dataset
m_health = pd.read_csv('D:\\Semester 3\\healthcare Analytics\\project\\survey.csv')

In [43]:
#see the data
m_health.head(10)

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN
5,2014-08-27 11:31:22,33,Male,United States,TN,NaN,Yes,No,Sometimes,6-25,...,Don't know,No,No,Yes,Yes,No,Maybe,Don't know,No,NaN
6,2014-08-27 11:31:50,35,Female,United States,MI,NaN,Yes,Yes,Sometimes,1-5,...,Somewhat difficult,Maybe,Maybe,Some of them,No,No,No,Don't know,No,NaN
7,2014-08-27 11:32:05,39,M,Canada,NaN,NaN,No,No,Never,1-5,...,Don't know,No,No,No,No,No,No,No,No,NaN
8,2014-08-27 11:32:39,42,Female,United States,IL,NaN,Yes,Yes,Sometimes,100-500,...,Very difficult,Maybe,No,Yes,Yes,No,Maybe,No,No,NaN
9,2014-08-27 11:32:43,23,Male,Canada,NaN,NaN,No,No,Never,26-100,...,Don't know,No,No,Yes,Yes,Maybe,Maybe,Yes,No,NaN

In [44]:
#information about data
#gives information about rows and column with non-null values so, we can find how munch null values we have in particuler columns.
m_health.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1259 entries, 0 to 1258
Data columns (total 27 columns):
Timestamp                    1259 non-null object
Age                          1259 non-null int64
Gender                       1259 non-null object
Country                      1259 non-null object
state                        744 non-null object
self_employed                1241 non-null object
family_history               1259 non-null object
treatment                    1259 non-null object
work_interfere               995 non-null object
no_employees                 1259 non-null object
remote_work                  1259 non-null object
tech_company                 1259 non-null object
benefits                     1259 non-null object
care_options                 1259 non-null object
wellness_program             1259 non-null object
seek_help                    1259 non-null object
anonymity                    1259 non-null object
leave                        1259 non-null object
mental_health_consequence    1259 non-null object
phys_health_consequence      1259 non-null object
coworkers                    1259 non-null object
supervisor                   1259 non-null object
mental_health_interview      1259 non-null object
phys_health_interview        1259 non-null object
mental_vs_physical           1259 non-null object
obs_consequence              1259 non-null object
comments                     164 non-null object
dtypes: int64(1), object(26)
memory usage: 265.7+ KB

In [45]:
#find unique values for age so, we can see remove unnecessary values which dosen't make sence in data
#here, we are finding unique values in particuler column
age_u = m_health['Age'].unique()
age_u.sort()
age_u

array([      -1726,         -29,          -1,           5,           8,
                11,          18,          19,          20,          21,
                22,          23,          24,          25,          26,
                27,          28,          29,          30,          31,
                32,          33,          34,          35,          36,
                37,          38,          39,          40,          41,
                42,          43,          44,          45,          46,
                47,          48,          49,          50,          51,
                53,          54,          55,          56,          57,
                58,          60,          61,          62,          65,
                72,         329, 99999999999], dtype=int64)

In [46]:
#drop rows which has unnessecery values in age column
#here, we are calling age column from m_health data where we are removing row where we find that unnessecery value in age column
m_health = m_health[m_health.Age != -1726]
m_health = m_health[m_health.Age != -29]
m_health = m_health[m_health.Age != -1]
m_health = m_health[m_health.Age != 329]
m_health = m_health[m_health.Age != 99999999999]
m_health = m_health[m_health.Age != 5]
m_health = m_health[m_health.Age != 8]
m_health = m_health[m_health.Age != 11]

In [47]:
#find unique values for age again to see clean values
age_u = m_health['Age'].unique()
age_u.sort()
age_u

array([18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       53, 54, 55, 56, 57, 58, 60, 61, 62, 65, 72], dtype=int64)

In [48]:
# again check information
m_health.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1251 entries, 0 to 1258
Data columns (total 27 columns):
Timestamp                    1251 non-null object
Age                          1251 non-null int64
Gender                       1251 non-null object
Country                      1251 non-null object
state                        738 non-null object
self_employed                1233 non-null object
family_history               1251 non-null object
treatment                    1251 non-null object
work_interfere               989 non-null object
no_employees                 1251 non-null object
remote_work                  1251 non-null object
tech_company                 1251 non-null object
benefits                     1251 non-null object
care_options                 1251 non-null object
wellness_program             1251 non-null object
seek_help                    1251 non-null object
anonymity                    1251 non-null object
leave                        1251 non-null object
mental_health_consequence    1251 non-null object
phys_health_consequence      1251 non-null object
coworkers                    1251 non-null object
supervisor                   1251 non-null object
mental_health_interview      1251 non-null object
phys_health_interview        1251 non-null object
mental_vs_physical           1251 non-null object
obs_consequence              1251 non-null object
comments                     161 non-null object
dtypes: int64(1), object(26)
memory usage: 273.7+ KB

In [49]:
#find unique values for gender
gender_u = m_health['Gender'].unique()
gender_u.sort()
gender_u

array(['Agender', 'Androgyne', 'Cis Female', 'Cis Male', 'Cis Man',
       'Enby', 'F', 'Femake', 'Female', 'Female ', 'Female (cis)',
       'Female (trans)', 'Genderqueer', 'Guy (-ish) ^_^', 'M', 'Mail',
       'Make', 'Mal', 'Male', 'Male ', 'Male (CIS)', 'Male-ish', 'Malr',
       'Man', 'Nah', 'Neuter', 'Trans woman', 'Trans-female', 'Woman',
       'cis male', 'cis-female/femme', 'f', 'femail', 'female', 'fluid',
       'm', 'maile', 'male', 'male leaning androgynous', 'msle',
       'non-binary', 'ostensibly male, unsure what that really means',
       'queer', 'queer/she/they', 'something kinda male?', 'woman'],
      dtype=object)

In [50]:
#replace the values for gender
m_health['Gender'] = m_health['Gender'].replace(['Cis Male', 'Cis Man','Guy (-ish) ^_^',
                                                 'M', 'Mail', 'Make', 'Mal', 'Male', 'Male ',
                                                 'Male (CIS)', 'Male-ish', 'Malr', 'Man','cis male',
                                                 'm', 'maile', 'male','msle'], "M")

m_health['Gender'] = m_health['Gender'].replace(['Cis Female','F', 'Femake', 'Female', 'Female ',
                                                 'Female (cis)','Woman','cis-female/femme', 'f',
                                                 'femail', 'female', 'woman'], "F")

m_health['Gender'] = m_health['Gender'].replace(['A little about you', 'Agender', 'Androgyne',
                                                 'Enby','Female (trans)', 'Genderqueer','Nah', 'Neuter', 'Trans woman',
                                                 'Trans-female','fluid','male leaning androgynous','non-binary',
                                                 'ostensibly male, unsure what that really means', 'queer',
                                                 'queer/she/they', 'something kinda male?'], "O")

In [51]:
#find unique values for gender again to see clean values
gender_u = m_health['Gender'].unique()
gender_u

array(['F', 'M', 'O'], dtype=object)

In [52]:
#see the data 
m_health.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,F,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,M,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,M,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,M,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,M,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [53]:
#here, we are droping three columns because commnets and state these two columns has more missing values and Timestamp has
#time and date which has around 3 month data so, we remove that also.
m_health = m_health.drop(['comments', 'state', 'Timestamp'], axis =1)

In [54]:
#Cleaning NaN
#Assign default values for each data type
#when there is integer column in data which has missing value then it put 0 in that missing value.
#if there is string column in data which has missing value then it put 'NaN' in that missing value.
int = 0 #default value for integers
string = 'NaN' #default values for string

#Create lists by data type
intFeatures = ['Age'] #integer features
stringFeatures = ['Gender', 'Country', 'self_employed', 'family_history', 'treatment', 'work_interfere',
                 'no_employees', 'remote_work', 'tech_company', 'anonymity', 'leave', 'mental_health_consequence',
                 'phys_health_consequence', 'coworkers', 'supervisor', 'mental_health_interview', 'phys_health_interview',
                 'mental_vs_physical', 'obs_consequence', 'benefits', 'care_options', 'wellness_program',
                 'seek_help'] #string features

#for loop which fills null values according to integer or string and if get any errors in columns then it gives error statement.
for feature in m_health:
    if feature in intFeatures:
        m_health[feature] = m_health[feature].fillna(int)
    elif feature in stringFeatures:
        m_health[feature] = m_health[feature].fillna(string)
    else:
        print('Error: Feature %s not recognized.' % feature)

In [55]:
m_health.head()

,Age,Gender,Country,self_employed,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37,F,United States,NaN,No,Yes,Often,6-25,No,Yes,...,Yes,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No
1,44,M,United States,NaN,No,No,Rarely,More than 1000,No,No,...,Don't know,Don't know,Maybe,No,No,No,No,No,Don't know,No
2,32,M,Canada,NaN,No,No,Rarely,6-25,No,Yes,...,Don't know,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No
3,31,M,United Kingdom,NaN,Yes,Yes,Often,26-100,No,Yes,...,No,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes
4,31,M,United States,NaN,No,No,Never,100-500,Yes,Yes,...,Don't know,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No

In [56]:
#Encoding data
#here, we are using label encoder to encode data
labelDict = {} #array named labelDict which we use as Dictionary
for feature in m_health:
    le = preprocessing.LabelEncoder() #labelEncoder
    le.fit(m_health[feature]) #fit the labelEncoder
    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_))) #original class and transform class
    m_health[feature] = le.transform(m_health[feature]) #transform data with all the features
    # Get labels
    labelKey = 'label_' + feature #labelKey which has label and feature names
    labelValue = [*le_name_mapping] #labelValue which has orinal class and transform class
    labelDict[labelKey] =labelValue #lebel dictonary
    
for key, value in labelDict.items(): #value which we transformed in labels except Age because it's already in numbers
    print(key, value)
    
m_health.to_csv('D:\\Semester 3\\healthcare Analytics\\project\\m_health.csv') #save data in .csv for future uses

label_Age [18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 53, 54, 55, 56, 57, 58, 60, 61, 62, 65, 72]
label_Gender ['F', 'M', 'O']
label_Country ['Australia', 'Austria', 'Belgium', 'Bosnia and Herzegovina', 'Brazil', 'Bulgaria', 'Canada', 'China', 'Colombia', 'Costa Rica', 'Croatia', 'Czech Republic', 'Denmark', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Hungary', 'India', 'Ireland', 'Israel', 'Italy', 'Japan', 'Latvia', 'Mexico', 'Moldova', 'Netherlands', 'New Zealand', 'Nigeria', 'Norway', 'Philippines', 'Poland', 'Portugal', 'Romania', 'Russia', 'Singapore', 'Slovenia', 'South Africa', 'Spain', 'Sweden', 'Switzerland', 'Thailand', 'United Kingdom', 'United States', 'Uruguay']
label_self_employed ['NaN', 'No', 'Yes']
label_family_history ['No', 'Yes']
label_treatment ['No', 'Yes']
label_work_interfere ['NaN', 'Never', 'Often', 'Rarely', 'Sometimes']
label_no_employees ['1-5', '100-500', '26-100', '500-1000', '6-25', 'More than 1000']
label_remote_work ['No', 'Yes']
label_tech_company ['No', 'Yes']
label_benefits ["Don't know", 'No', 'Yes']
label_care_options ['No', 'Not sure', 'Yes']
label_wellness_program ["Don't know", 'No', 'Yes']
label_seek_help ["Don't know", 'No', 'Yes']
label_anonymity ["Don't know", 'No', 'Yes']
label_leave ["Don't know", 'Somewhat difficult', 'Somewhat easy', 'Very difficult', 'Very easy']
label_mental_health_consequence ['Maybe', 'No', 'Yes']
label_phys_health_consequence ['Maybe', 'No', 'Yes']
label_coworkers ['No', 'Some of them', 'Yes']
label_supervisor ['No', 'Some of them', 'Yes']
label_mental_health_interview ['Maybe', 'No', 'Yes']
label_phys_health_interview ['Maybe', 'No', 'Yes']
label_mental_vs_physical ["Don't know", 'No', 'Yes']
label_obs_consequence ['No', 'Yes']